FROM node:17

WORKDIR /

COPY . .

RUN yarn install;
RUN npm install;

ENV PORT=3000
ENV HOST="35.194.219.59"
ENV DB_PORT=5432
ENV DB="SDM"
ENV USER_NAME="admin"
ENV PASSWORD="cloud123"
ENV MAP_API_KEY="AIzaSyB2tLbNMQjOOND77CUnDgWottYd9RCm_O4"

ENV WEBHOOK_SECRET_ADD="whsec_vvBNCOWozTR/Vqlj6/m7Do71ZoMmy8xd"
ENV NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY="pk_test_aW1tZW5zZS1zYWlsZmlzaC00Ni5jbGVyay5hY2NvdW50cy5kZXYk"
ENV CLERK_SECRET_KEY="sk_test_NKFcfAjahnwcr8KQGwLsT33g2hxN7k7rUIzV3TDxWZ"

RUN echo "PORT = $PORT"
RUN echo "HOST = $HOST"

CMD ["yarn", "start"]

